# Generated by Django 5.1.4 on 2025-01-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management', '0004_alter_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (0, 'Unpaid')])),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
        ),
    ]
