# Generated by Django 5.1.4 on 2025-01-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0001_initial'),
        ('student_management', '0005_alter_student_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payement',
            new_name='Payment',
        ),
    ]
