# Generated by Django 5.1.4 on 2025-01-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_alter_room_room_number'),
        ('student_management', '0003_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostel_management.room'),
        ),
    ]
