# Generated by Django 5.1.4 on 2025-01-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_alter_room_room_number'),
        ('student_management', '0004_alter_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.room'),
        ),
    ]
