# Generated by Django 5.1.4 on 2025-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_student_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='check_in',
            field=models.DateField(),
        ),
    ]
